### ISSUE TITLE
Make test suite

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#1]

**Comment by sckott** [comment]
- [ ] `changes`
- [ ] `ds_create`
- [ ] `ds_create_dataset`
- [ ] `ds_search`
- [ ] `ds_search_sql`
- [ ] `get_ckanr_url`
- [ ] `group_list`
- [ ] `group_show`
- [ ] `license_list`
- [ ] `organization_list`
- [ ] `organization_show`
- [ ] `package_activity_list`
- [ ] `package_list`
- [ ] `package_list_current`
- [ ] `package_revision_list`
- [ ] `package_search`
- [ ] `package_show`
- [ ] `ping`
- [ ] `resource_search`
- [ ] `resource_show`
- [ ] `revision_list`
- [ ] `set_ckanr_url`
- [ ] `tag_list`
- [ ] `tag_search`
- [ ] `tag_show`
- [ ] `user_list`

**Comment by sckott** [comment]
started testing 7d279d2d1461589ff1af67aeaec7748a575d7c10

**Comment by wush978** [comment]
Dear @sckott ,

Currently, I don't know how to test `user_list`(please see #26 ), `ds_create` and `ds_create_dataset`. For `ds_create`, I tried to run the example script but got: 409 Conflict. For `ds_create_dataset`, I got 403 Forbidden.

Except these 3 functions, all tests are done( #27 ). However, I only check the returned type. At least these tests make sure that these function get 200 from CKAN server.

**Comment by sckott** [comment]
now we just have `ds_create` and `ds_create_dataset` remaining

**Comment by sckott** [comment]
I still can't get `ds_create()` to work, I haven't yet figured out what format they want the data in, seems like it's simple json, but nothing working yet

**Comment by sckott** [comment]
only `ds_create` test remaining, closing as basically done
