### ISSUE TITLE
organization related features

### ISSUE THREAD

**Issue by wush978** [ropensci/ckanr#10]
Dear maintainers,

I am a co-funder of a start-up which provides tutorial services for data science. We choose the CKAN as a management system for the example datasets and we choose R to be our major toolset in our product. Thanks for your great work so that we can integrate our tutorial with CKAN more easily.

There are some use case of us that required API which `ckanr` does not implement. For example, the organization related features, the decode of unicode code print, and the authentication of API-Key. 

I am also a package developer of R, so it is easy for me to customize the `ckanr` for us. However, I want to discuss with you that if I could contribute these features for you. For example, the feature of organization related features.

Thanks,
Wush

**Comment by sckott** [comment]
hi @wush978 - Glad to see other people interested in this!

That would be great if you are willing to contribute changes back here. Feel free to send pull requests to this repo when you're ready.
