### ISSUE TITLE
package_list returns ERROR

### ISSUE THREAD

**Issue by noeliaoses** [ropensci/ckanr#104]
<details> <summary><strong>Session Info</strong></summary>

Session info -----------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.136)           
 language en_GB:en                    
 collate  en_GB.UTF-8                 
 tz       Europe/Madrid               
 date     2018-07-18                  

Packages ---------------------------------------------------------------------------------------------------------
 package   * version date       source         
 base      * 3.4.4   2018-03-16 local          
 ckanr     * 0.1.0   2015-10-22 CRAN (R 3.4.4) 
 compiler    3.4.4   2018-03-16 local          
 curl        2.7     2017-06-26 CRAN (R 3.4.1) 
 datasets  * 3.4.4   2018-03-16 local          
 devtools    1.13.2  2017-06-02 CRAN (R 3.4.1) 
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0) 
 graphics  * 3.4.4   2018-03-16 local          
 grDevices * 3.4.4   2018-03-16 local          
 httr      * 1.3.1   2017-08-20 CRAN (R 3.4.4) 
 jsonlite  * 1.5     2017-06-01 CRAN (R 3.4.1) 
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0) 
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.1) 
 methods   * 3.4.4   2018-03-16 local          
 R6          2.2.2   2017-06-17 CRAN (R 3.4.1) 
 Rcpp        0.12.12 2017-07-15 cran (@0.12.12)
 stats     * 3.4.4   2018-03-16 local          
 tools       3.4.4   2018-03-16 local          
 utils     * 3.4.4   2018-03-16 local          
 withr       2.0.0   2017-07-28 CRAN (R 3.4.2) 
 xml2        1.1.1   2017-01-24 CRAN (R 3.4.1) 

</details>

Hi, I've just installed ckanr and are learning to use it. At the moment I'm interested in EU's open data. When I run

`GET("http://data.europa.eu/euodp/data/api/3/action/package_list")`

I get the expected result. However, if I do:

```
require(ckanr)
ckanr_setup(url = "http://data.europa.eu/euodp/data/api/3/action")
package_list()

```
what I get is "Error: "
What is the problem? 
Any help is much appreciated!
noelia

**Comment by sckott** [comment]
thanks for your question @noeliaoses ! 

`ckanr_setup` is looking for a base URL, so not the complete thing, try e.g. 

```r
ckanr_setup(url = "http://data.europa.eu/euodp/data")
package_list()
```

**Comment by noeliaoses** [comment]
Thanks @sckott !

That got rid of the error message. However, when I use GET("http://data.europa.eu/euodp/data/api/3/action/package_list") I get a list of over 12k packages but the way you suggested I only get 31. Any idea why?

Thanks a lot!!

**Comment by sckott** [comment]
Did you read the documentation yet? see `?package_list`, see the `limit` parameter in particular
