### ISSUE TITLE
How to specify a proxy?

### ISSUE THREAD

**Issue by JanDuo** [ropensci/ckanr#105]
<details> <summary><strong>Session Info</strong></summary>

```r
> sessionInfo() R version 3.4.3 (2017-11-30) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 7 x64 (build 7601) Service Pack 1  Matrix products: default  locale: [1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252    [3] LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                       [5] LC_TIME=Dutch_Netherlands.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] ckanr_0.1.0          RevoUtils_10.0.8     RevoUtilsMath_10.0.1  loaded via a namespace (and not attached):  [1] httr_1.3.1      compiler_3.4.3  magrittr_1.5    R6_2.2.2         [5] rsconnect_0.8.5 tools_3.4.3     curl_3.1        yaml_2.1.16      [9] knitr_1.18      jsonlite_1.5
--
 
```
</details>

I'm using RStudio on a Windows7 environment. It's located behind a proxy, but with the global option "Use Internet Explorer library/proxy for HTTP" ticked I can download packages without issues.

But when I try to run the next piece of code I run into connection issues. 
```{r}
library(ckanr)
ckanr_setup(url = "http://data.nhm.ac.uk")
package_list(as = "list")
```
Error in curl::curl_fetch_memory(url, handle = handle) : Timeout was reached: Connection timed out after 10016 milliseconds
8. curl::curl_fetch_memory(url, handle = handle)
7. request_fetch.write_memory(req$output, req$url, handle)
6. request_fetch(req$output, req$url, handle)
5. request_perform(req, hu$handle$handle)
4. VERB(file.path(url, ck(), method), body = body, ...)
3. ckan_VERB("POST", url, method, body, key, ...)
2. ckan_POST(url, method = "package_list", key = NULL, body = tojun(body, TRUE), encode = "json", ctj(), ...)
1. package_list(as = "list")

When I try http://data.nhm.ac.uk/api/3/action/package_list in my browser I do get the JSON with the package list immediately.

Is there a way to specify/define a proxy in the ckanr functions?

**Comment by sckott** [comment]
thanks for your question @JanDuo - looking at it now

**Comment by sckott** [comment]
@JanDuo can you reinstall `remotes::install_github("ropensci/ckanr")` and try again, see `?ckanr_setup` after installing for an example of setting proxy

**Comment by JanDuo** [comment]
Thanks a lot! This solved my problem. The next piece of code does give the package list as expected.

```{r}
library(ckanr)

the_proxy <- httr::use_proxy(url = curl::ie_get_proxy_for_url("http://ttp://data.nhm.ac.uk"))

ckanr_setup(url = "http://data.nhm.ac.uk", proxy = the_proxy)
package_list(as = "list")
```
