### ISSUE TITLE
Update repository description

### ISSUE THREAD

**Issue by amercader** [ropensci/ckanr#110]
Hi, CKAN maintainer here. Congratulations on the amazing tool, and thanks for contributing to the CKAN ecosystem! I just wanted to suggest a small change in the repository description. The REST API has been deprecated for a long time and removed in recent versions, so to avoid confusion perhaps is better to use "R client for the CKAN Action API" (or just "R client for the CKAN API").

**Comment by sckott** [comment]
👋 thanks for the suggestion. Do you have a preference on "Action API" vs. "API"?

**Comment by amercader** [comment]
No strong preference. Perhaps "CKAN API" is what most of your users care about :)

**Comment by sckott** [comment]
will make the change. 

(off topic: while I have you here, i've always wanted to be able to test this pkg against a real CKAN instance that I can spin up myself. ideally something I can spin up on Travis or circle-ci or so. any ideas?)

**Comment by jqnatividad** [comment]
Hi @sckott , 
In terms of a test instance, my organization - Datopian, might be able to help with that.

Dunno if its something that you can spin up with Travis or circle-ci, but we can certainly host a test instance, that perhaps, with the [CKAN API](https://github.com/ckan/ckanapi), you can automatically delete/insert datasets as part of testing.

Let me know...

**Comment by amercader** [comment]
Hey, Sorry I missed this. No need to setup a live instance somewhere, all CKAN extensions tests run in Travis set one up on each run. I'll send a PR early this week that you can tweak if needed.

**Comment by sckott** [comment]
thanks @jqnatividad for the offer, i'll look into the offer from @amercader first though I think

@amercader thanks, a PR would be great

**Comment by sckott** [comment]
description for repo changed.
