### ISSUE TITLE
Is there any function in ckanr can arrange package last modified date directly?

### ISSUE THREAD

**Issue by jaesm14774** [ropensci/ckanr#111]
Hi, everyone

I meet some problems in my project, so ask for help.I'm glad to hear some idea about this question .

Q1:
Is there any function in ckanr can arrange last modified date  of package directly(e.g. from new to last)?Not use package_show(id) because it takes many times if exist many packages.

I want to do some project like crawl data from website whose structure is ckan, do some operation to all data, and then update all revised data. If old data in that website is updated,I have to download it and do the same thing as above.
Then it was a question for how can I know the data it is updated without using package_show comment to know information of packages.

Q2:
Why can I  get same order of list when I use package_list comment?
How does this comment arrange?

If anyone can share your idea to solve these questions, I will be happy.
Thanks anyone seeing this question  last.

**Comment by florianm** [comment]
Hi @jaesm14774 - some pointers:

I can't find or don't remember a way of ordering `package_list` by attributes, such as dates of last change. However, you can [get a list of package (revisions) based on a last changed date](https://docs.ckan.org/en/latest/api/#ckan.logic.action.get.revision_list).

Crawling a CKAN: I've done some similar work, crawling ArcGIS Server REST and populating CKAN from that - at least some working examples: https://github.com/datawagovau/harvesters

Hope that helps!

**Comment by sckott** [comment]
thanks @florianm 

@jaesm14774  for your 2nd question 

> Why can I get same order of list when I use package_list comment?

Can you re-phrase this? I can't quite understand what you are asking.

**Comment by jaesm14774** [comment]
@florianm  Thank you very much.It's just what I want .

@sckott  Ok. I use this comment like image below in other programming.And I get the same order package id by this comment.Then the question is how package order.Is it some rule to order id of package?
e.g. first time running this comment:[0001,0005,asd,004,....]
       second time running this comment:[0001,0005,asd,004,....]
       ...
 All is same order whatever I run this comment.
![image](https://user-images.githubusercontent.com/33981395/57265971-833cda80-70ac-11e9-9159-253ab591caa0.png)

Thanks for your reply.

**Comment by florianm** [comment]
Second-guessing here:

* CKAN determines the order of API responses, ckanr is just a wrapper around the CKAN API. To figure out where the ordering of packages in `package_list` comes from, you could read the CKAN code or search CKAN stackoverflow questions in regards to ordering of the response.
* Rather than relying on the order of the response (addressing by position) you could match by package ID (addressing by key). Wild guess from me, this is.

**Comment by sckott** [comment]
thanks again @florianm 

@jaesm14774 did we address all your questions?

**Comment by jaesm14774** [comment]
Yes,Thanks.
