### ISSUE TITLE
ckan_fetch() fails when resource URL doesn't contain file format

### ISSUE THREAD

**Issue by sharlagelfand** [ropensci/ckanr#116]
In updating the examples for `ckan_fetch()`, I ran into a lot of cases where the file format isn't actually in the resource URL and so `ckan_fetch()` fails (somewhat uninformatively):

``` r
library(ckanr)
#> Loading required package: DBI

ckanr_setup("https://data.europa.eu/euodp/data/")
res <- resource_show(id = "f2cfb3f8-44f6-4027-952f-a1d759484501", as = "table")

res$url
#> [1] "http://www.emcdda.europa.eu/data/stats2018/dlo"
res$format
#> [1] "HTML"

ckan_fetch(res$url, format = "")
#> Error in if (file_fmt(x) == "xls") {: argument is of length zero
```

<sup>Created on 2019-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

From what I've seen, the file format is often (always? I'm not a CKAN expert) available in that `res` object. Would you be interested in a PR for an optional `format` argument to `ckan_fetch()`? It could either be taken straight from the `res` object or just user-specified.

**Comment by sckott** [comment]
I think that makes sense to add a format parameter. it'd be interesting to see if `resource_show` ever returns the wrong format type for the file, hopefully it's always right, or at least most of the time

**Comment by sharlagelfand** [comment]
cool! yeah, i'm not entirely clear on how that field is populated. 

my thought was to take the format from the URL if it's available, and only use the user-supplied (via `resource_show()` or manually) if it's not. do you think it would make more sense to do that, or to have the user-supplied one supersede what's found from the URL? hopefully they'd always be the same, but if they're not... 🙃

**Comment by sckott** [comment]
i was trying to say that the `format` key is in the response body from the CKAN server - e.g,. try 

```sh
curl https://ckan0.cf.opendata.inter.sandbox-toronto.ca/api/3/action/resource_show?id=6cbb0aa3-a8d1-421c-9c40-14c6f05e0c73 | jq .result.format
# or without jq if you don't have it
curl https://ckan0.cf.opendata.inter.sandbox-toronto.ca/api/3/action/resource_show?id=6cbb0aa3-a8d1-421c-9c40-14c6f05e0c73
```

jq - https://stedolan.github.io/jq/

**Comment by sharlagelfand** [comment]
yep! sorry, by "user-supplied" i meant the one they'd specify in the `format` argument, likely from `resource_show()`, rather than whatever is derived from the URL via `file_fmt(x)`

**Comment by sckott** [comment]
right, there is the format guessed within `ckan_fetch` within `fetch_GET`, but i thought when you referred to `res` you mean the result from the call to `resource_show`, which is directly from the data returned from CKAN

**Comment by sharlagelfand** [comment]
yes, i did! i think we're talking about the same thing and that my original question wasn't very clear.

i'm just curious to see if there would be cases where the format guessed (via `file_fmt(x)`) doesn't match the user input (from `resource_show()`, e.g. `resource_show` returns the wrong format) and in that case, which should be chosen as the "true" format. does that make more sense?

**Comment by sharlagelfand** [comment]
i feel like i'm confusing myself more than anything. i'll just work on a PR and we can talk about it more concretely!

**Comment by sckott** [comment]
sounds good
