### ISSUE TITLE
ckan_fetch writes to working directory when store = "session"

### ISSUE THREAD

**Issue by sharlagelfand** [ropensci/ckanr#125]
i noticed that `ckan_fetch()` writes the file to disk (the working directory) in most cases when `store = "session"` (e.g. https://github.com/ropensci/ckanr/blob/master/R/zzz.R#L73). would you consider having it write to a temporary file instead and then reading from there? 

i've been looking a little at what `rio::import()` does and that seems to be the strategy (e.g., see [`remote_to_local()`](https://github.com/leeper/rio/blob/master/R/remote_to_local.R)). 

i have a feeling that writing to disk without explicit consent might be an issue for CRAN submission too (https://twitter.com/_ColinFay/status/1146675312866074625).

if you think this is a good idea then i can work on a PR to do this. thanks!

**Comment by sckott** [comment]
thanks @sharlagelfand 

agree we should write it to a temporary file - PR sounds good
