### ISSUE TITLE
Use stringsAsFactors = FALSE for CSV files in `ckan_fetch() / read_session()`?

### ISSUE THREAD

**Issue by LVG77** [ropensci/ckanr#141]
First, I would like to thank you for this wonderful package!

This is not exactly an issue but rather a question. I am wondering if it wouldn't make sense to have `stringsAsFactors = FALSE` when fetching .csv files with `ckan_fetch() / read_session()`? It would make the reading of the data faster and also it is not always useful to have all non-numeric columns converted to factors automatically.

Please let me know what you think.

Cheers,
LG

**Comment by sckott** [comment]
Thx for the issue @LVG77 

@sharlagelfand thoughts?

**Comment by sharlagelfand** [comment]
makes sense to me to change! i can PR it
