### ISSUE TITLE
update version on CRAN?

### ISSUE THREAD

**Issue by sharlagelfand** [ropensci/ckanr#143]
hey Scott,

I'm looking to submit opendatatoronto to CRAN - no specific timeline, but figured it'd be nice to get it on there. right now it depends on a lot of newer features in ckanr and needs the dev/github remote version, which seems like a no-no for CRAN.

curious if you have plans to resubmit to CRAN or want to wait until e.g. version 0.4 to do that. happy to take a look at some issues or do what i can to help out if you're waiting on anything.

thanks!
sharla

**Comment by sckott** [comment]
thanks for the note. Looks like we're all set, no open issues on current milestone https://github.com/ropensci/ckanr/milestone/3 

will try to get up today/tomorrow

**Comment by sharlagelfand** [comment]
ah amazing, thank you!

**Comment by sckott** [comment]
about ready to send
