### ISSUE TITLE
CKAN for testing

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#144]
Try creating a single CKAN image with all parts needed, and put on docker hub, then be able to use that image in circle-ci or travis. 

Following steps for installation https://docs.ckan.org/en/2.8/maintaining/installing/install-from-docker-compose.html 

docker-compose with multiple images https://github.com/dbca-wa/wastd/blob/master/.circleci/config.yml

**Comment by sckott** [comment]
This spins up nicely locally https://github.com/okfn/docker-ckan Maybe make the images locally, push up to my docker hub, then pull those for CI testing/checking

**Comment by sckott** [comment]
Notes: 

- on branch `ckan-on-gh-actions` working on this
- maybe use this https://github.com/peter-evans/docker-compose-actions-workflow
- caching docker images https://github.com/marketplace/actions/docker-layer-caching
- help on docker on gh actions https://github.community/t/how-to-use-docker-compose-with-github-actions/16850 
- repo im using https://github.com/okfn/docker-ckan

**Comment by florianm** [comment]
Nice work! There's a GH action to add a live SSH terminal. That would be ideal to debug where CKAN might be running. Maybe GHA has some firewall settings to hide the open ports?
