### ISSUE TITLE
Support for Arbitrary Key:Value Pairs When Creating Resources

### ISSUE THREAD

**Issue by nicholsn** [ropensci/ckanr#149]
I have a use case where I would like to attach arbitrary `key:value` pairs to a given resource. 

While this is currently possible via `resource_patch`, it is not possible when initially creating a resource, as `resource_create` explicitly specifies each of the permitted parameters.

I've tested that this works via curl, but curious if this would an acceptable feature request for `resource_create`.

If so, I can work on a PR to add this functionality - or maybe I missed something and this is already supported - just let me know!

**Comment by sckott** [comment]
thanks for the issue 

> While this is currently possible via resource_patch

It is? there is an ellipsis (`...`) for `resource_patch`, but that's for passing in curl options to the HTTP request. Did you mean `package_patch` via `extras`?

Would doing this via `extras` work for you?

**Comment by nicholsn** [comment]
Hey @sckott, thanks for getting back to me.

Actually, resources support `key:value` pairs w/o the package-level "extras" field that uses a list of:

```javascript
"extras": [
    {"key": "some-key", "value": "some-value"}
]
```

At the resource-level in `resource_patch` you can just use the `x` parameter and include whatever `k:v` pairs you'd like and they will be added directly to the resource json object (I just learned this was possible [here](https://stackoverflow.com/questions/15709586/attach-extras-to-ckan-resources)). For example:

```R
data <- resource_patch(x = list(
    package_id = "my-package-id",
    url = "http://google.com",
    name = "Google",
    some-key = "some-value"
))
```

Also confirmed directly in the API with a curl-like tool.
```
# https://httpie.org/
http http://localhost:5000/api/3/action/resource_create Authorization:S3creTe package_id=new-data-1 url=http://localhost.com foo=bar
```
So, I am just wondering how that feature would best fit into resource_create. Curious to hear your thoughts!

**Comment by sckott** [comment]
okay, thanks. Is that documented anywhere?

**Comment by nicholsn** [comment]
not that I've seen. the closest thing is this: https://docs.ckan.org/en/ckan-2.7.3/extensions/adding-custom-fields.html#adding-custom-fields-to-resources

**Comment by sckott** [comment]
Okay, hmm, im a bit hesitant to include this if it's not documented, but i imagine i've done that with other aspects here before. 

Do you know what other CKAN API routes this applies to?

**Comment by nicholsn** [comment]
I went ahead and pinged the ckan mailing list to ask about [this feature and adding docs](https://groups.google.com/a/ckan.org/forum/#!topic/ckan-dev/3WCSgKjh-I0). We can wait and see what they say.

As far as I can tell, the only CKAN API routes this applies to are `resource_create`, `resource_update`, and `resource_patch`, and in the ckanr code, I think only `resource_create` needs to be updated (although we could add an example of usage to the others).

**Comment by sckott** [comment]
thanks for pinging the mailing list. sounds best to wait to see what folks say over there

**Comment by florianm** [comment]
From the CKAN code base:
* `resource_patch` simply updates the resource's data dict - allows extra fields: https://github.com/ckan/ckan/blob/master/ckan/logic/action/patch.py#L54
* The model for Resource allows `extra_columns`: https://github.com/ckan/ckan/blob/master/ckan/model/resource.py#L58
* The template for `resource_read` (the resource details page) renders any extra fields in the key:value table: https://github.com/ckan/ckan/blob/master/ckan/templates/package/resource_read.html#L204

None of those prevent adding any extras to resources, so `resource_patch/update/create` will just accept any additional key-value pairs.

Caveats I'm aware of:

* The solr search index might not index custom extra fields unless you configure those in the solr `schema.xml`
* The docs mention some [cosmetic surgery on the templates](https://docs.ckan.org/en/2.8/extensions/adding-custom-fields.html#sorting-by-custom-fields-on-the-dataset-search-page) to support extra fields
* If you use a custom schema through ckanext-scheming, these custom fields can override the extra fields in the templates, so extra care has to be taken by users of ckanext-scheming not to `resource_update/path/create` fields into their CKAN that their custom schema doesn't expect.

**Comment by sckott** [comment]
thanks for the deets @florianm 

@nicholsn does florian's info help/change anything?

**Comment by nicholsn** [comment]
thanks @florianm! 

@sckott I think these details confirm that it would be safe to add this functionality to ckanr for the `resource_patch/update/create`. If you agree, I can look into submitting a PR, but just looks like a small change.

**Comment by sckott** [comment]
okay, a PR would be great - always nice to have more contribs

**Comment by sckott** [comment]
@nicholsn let me know if your PR resolves this issue

**Comment by nicholsn** [comment]
Indeed, thanks for merging!
