### ISSUE TITLE
package_search() error when x$title is a list

### ISSUE THREAD

**Issue by ismailmuller** [ropensci/ckanr#152]
I tried this package for the first time but came across an error.
It seems that `x$title` is a list and not supported by the `cat` function used in `ckanr:::as.ckan_package()`.

``` r
library(ckanr)
#> Le chargement a nécessité le package : DBI

ckanr::ckanr_setup(url = "http://opendata.swiss")
pkg <- "ladestationen-fuer-elektroautos"

# Check if it exists
pkgs <- ckanr::package_list(limit = 10000, as = "table")
any( pkgs == pkg )
#> [1] TRUE

# package_search() gives an error
ckanr::package_search(pkg)
#> $count
#> [1] 4778
#> 
#> $sort
#> [1] "score desc, metadata_modified desc"
#> 
#> $facets
#> named list()
#> 
#> $results
#> $results[[1]]
#> <CKAN Package> df6ecca9-1097-46ad-aa71-97f3f1a32f51 
#>   Title:
#> Error in cat("  Title: ", x$title, "\n", sep = ""): argument 2 (type 'list') pas encore traité par cat
```

<sup>Created on 2020-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sckott** [comment]
thanks very much @ismailmuller - having a look

**Comment by sckott** [comment]
reinstall `remotes::install_github("ropensci/ckanr")` - should work now, let me know what you think. it's not clear how we would pick from the list of locale specific results in the list - we could query the ckan instance for the default locale, but that's another http request

**Comment by ismailmuller** [comment]
Thanks a lot @sckott . It does the job now without failing.
