### ISSUE TITLE
Default CKAN url in a bad way

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#161]
http://data.techno-science.ca seems to be not responding

http://techno-science.ca redirects to https://ingeniumcanada.org/ 

https://data.ingeniumcanada.org/ is not a thing, maybe there is a different ckan url for that new site?

@florianm @sharlagelfand any ideas on this? should we switch to a different CKAN instance

**Comment by sharlagelfand** [comment]
oh no! i didn't see the original instance but it looks like maybe Ingenium has switched (?) to having all of their open data available as a single, downloadable data set (https://ingeniumcanada.org/collection-research/open-data links to https://ingeniumcanada.org/collection-research/artifact-open-data-set-mash-up, which just has links to download a giant .xml or .csv)

Biased option from me for a different default is [Ontario's open data catalogue](https://data.ontario.ca/) which has a pretty solid team backing it and doesn't seem like it'll go anywhere

**Comment by sckott** [comment]
Thanks @sharlagelfand !

Ontario sounds good, will try that

**Comment by florianm** [comment]
I don't have a public instance available for testing unfortunately. Can rOpenSci host one in a VM?

**Comment by sckott** [comment]
I have a t3 micro reserved instance on Amazon that I can't sell back to them, so I could use that until jan 2022, but maybe that's too small an instance to run ckan. what's the minimum setup for running via docker vs. installing via the package route

**Comment by florianm** [comment]
There's nothing re minimum hardware requirements in the official docs, but the Wiki suggests: https://github.com/ckan/ckan/wiki/Hardware-Requirements
Seems a t3.small to medium might be required, but maybe it's worth to try a package install on the t3.micro?
A second option could be a CKAN install inside GitHub Actions.

**Comment by sckott** [comment]
yeah, i don't think i want to pay for anything bigger than the micro. 

i'd love to be able to spin up ckan on GH actions, any example workflows doing that?

**Comment by florianm** [comment]
Nothing on GHA marketplace, nothing in CKAN's own [actions](https://github.com/ckan/ckan/actions) so basically one would need to translate the [docs](https://docs.ckan.org/en/2.9/maintaining/installing/install-from-package.html) into a GHA script. Handy to add a [debug action](https://github.com/marketplace/actions/debugging-with-tmate) to bite your way through the setup.
