### ISSUE TITLE
update servers function

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#162]
those that are not CKAN anymore, or at least appear not to be:

- https://data.gov.uk/
- http://data.london.gov.uk - appears to be using https://datapress.com/
- http://publicdata.eu/ - is gone
- http://data.surrey.ca/ - appears to be down

**Comment by sckott** [comment]
probably should freshen up urls behind `servers` fxn too

**Comment by florianm** [comment]
data.gov.uk seems highly customised, maybe to the point where it's not a good example of "vanilla CKAN" any longer.
There seems to be a CKAN in there: https://github.com/alphagov/docker-ckan and their own CKAN extension https://github.com/alphagov/ckanext-datagovuk/.

Would it be an option for rOpenSci to run their own CKAN (e.g. using docker-compose) in a dedicated VM?

**Comment by sckott** [comment]
Thanks for the dive into that source - chatting about running ckan in another issue
