### ISSUE TITLE
Mexico and datamx.io open data in servers.R

### ISSUE THREAD

**Issue by nn-at** [ropensci/ckanr#174]
http://datamx.io/ does not appear to exist any more, it may have been replaced by the Government of Mexico's current open data catalogue https://datos.gob.mx/desarrolladores 

Is the latter using a version compatible with ckanr and could be added?

**Comment by sckott** [comment]
That 2nd url gives me `Access Denied`

**Comment by nn-at** [comment]
works for me in browser, and they have an entire section on CKAN and another on their CKAN API, although it's all in Spanish and Google Translate isn't working for me atm so I'm kind of guessing at what they are saying.

**Comment by sckott** [comment]
Ok, but I still can't access it, which means other people will likely have trouble accessing it, so I'd rather not include it
