### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/ckanr#186]
Or new maintainer team. :smile_cat: 

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html).

**Comment by fjuniorr** [comment]
Hi @maelle!

I would love to help resolve some of the outstanding issues as a "trial period" to see if I'm able to actually take over the package maintenance. Is that a thing?

**Comment by maelle** [comment]
:wave: @fjuniorr! Yes let's make it a thing, that's a good idea. You can make PRs that I'd review if you want?

**Comment by maelle** [comment]
Feel free to ask any question!

**Comment by fjuniorr** [comment]
Hi @maelle! I don't think I have permission to add you as reviewer in the PR but I just sent over #190. 

Before making changes I want to make sure that the testing infrastructure works both locally and in Github Actions without dependencies on external CKAN sites.

**Comment by maelle** [comment]
@fjuniorr would you like to be invited to rOpenSci slack workspace?

**Comment by fjuniorr** [comment]
That would be great @maelle!

**Comment by fjuniorr** [comment]
Yeah! I should probably also add myself as maintainer, right?

**Comment by maelle** [comment]
Yes! :tada: and thank you!!

**Comment by florianm** [comment]
Hi @maelle, 
@fjuniorr has reached out to me and I'd like to volunteer to take over maintainership of the ckanr package. What would be the best process to follow?

**Comment by maelle** [comment]
Thanks @fjuniorr for your work on the package!
@florianm Thank you for volunteering! I've now added you to a team with admin access to this repository. Please update DESCRIPTION (keeping @fjuniorr as aut, updating your role to aut+cre). I'd also recommend submitting to CRAN soon-ish (@fjuniorr will have to ok the change of maintainer).

**Comment by florianm** [comment]
@maelle Thanks, that was fast! I'll address the author changes this week. Do you suggest submitting the current version as is, only with updated personnel in DESCRIPTION, to CRAN?

**Comment by maelle** [comment]
Since the CRAN check results are ok and the former maintainer is still responsive, I think you can wait until you have made the other changes you'd like to put in the next release. Only my two cents! 😇
