### ISSUE TITLE
err_handler produces error

### ISSUE THREAD

**Issue by wush978** [ropensci/ckanr#19]
Dear @sckott ,

The `err_handler` in https://github.com/ropensci/ckanr/commit/7d279d2d1461589ff1af67aeaec7748a575d7c10#diff-e549505eb95036528ca3b125f62915a6R29 produces `Error in content(x)$error : 
  object of type 'externalptr' is not subsettable` when I want to access a local ckan server here.

The reason is that the returned 404 http response contains a webpage which is parsed as `HTMLInternalDocument` from `httr::content`(https://github.com/ropensci/ckanr/commit/7d279d2d1461589ff1af67aeaec7748a575d7c10#diff-e549505eb95036528ca3b125f62915a6R31) and the subsetting `$error` produces this error.

I save the response object here: <https://www.dropbox.com/s/06rqjjo13cwo0tz/404.Rds?dl=0>.

Wush

**Comment by wush978** [comment]
I modify the `err_handler` in https://github.com/wush978/ckanr/commit/a46ed76659242b8cefe9fc5067f348c48607287a . If you like it, I could give you a PR.

**Comment by sckott** [comment]
I figured that might not work in all cases. Yes, plz do send the PR
