### ISSUE TITLE
Different behavior of travis-ci

### ISSUE THREAD

**Issue by wush978** [ropensci/ckanr#23]
Dear @sckott ,

I notice that the result of travis-ci of wush978/ckanr is different from travis-ci of ropensci/ckanr. Mine always stops at the beginning due to: "sudo: must be setuid root". Could you tell me whether you did any additional configuration in travis-ci?

Thanks,
Wush

**Comment by sckott** [comment]
Many R pkgs are failing now b/c of that. It's something about container usage that I don't fully understand. It doesn't hurt to add I think, so I'll add that to the travis file, and should fix yours

**Comment by wush978** [comment]
Thank you very much! It works.
