### ISSUE TITLE
default parameter of resource_search

### ISSUE THREAD

**Issue by wush978** [ropensci/ckanr#25]
Dear @sckott , 

The default value of parameter `q` of `resource_search` does not make sense. First, `q` must be given because there is no default value given in the definition of `resource_search`. Second, `*:*` does not work with `resource_search`.

The `q="name:data"` works so I will use it for testing.

**Comment by sckott** [comment]
it seems they don't set a default either http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.resource_search I guess i had `*:*` as a default carrying over from another pkg i work on. 

I removed that line about `*:*` from the parameter definition - the `q` parameter doesn't currently have a default, so if called `resource_search()` it just errors saying `q` is missing.  For testing, what you use seems good.

**Comment by sckott** [comment]
@wush978  okay to close?

**Comment by wush978** [comment]
Yes, thanks!
