### ISSUE TITLE
Include more examples with data providers that use CKAN in examples

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#3]

**Comment by florianm** [comment]
FYI the [shiny-timeseries-explorer](https://yes-we-ckan.shinyapps.io/shiny-timeseries/) uses ckanr to talk to CKAN. Its "upload to CKAN" functionality is the reason I'm contributing to ckanr :-) 

Feel free to take it for a whirl (your data-demo.dpaw.wa.gov.au API key will work in that app).

**Comment by sckott** [comment]
great, thanks @florianm
