### ISSUE TITLE
Set CKAN url, key, dataset and resource id for testing

### ISSUE THREAD

**Issue by florianm** [ropensci/ckanr#30]
Is there a clever way to set a CKAN url, key, dataset and resource id for testing of the create/update/delete functions once (they will vary between developers/testers) and use them in tests?

**Comment by sckott** [comment]
does #31 address this?

**Comment by florianm** [comment]
added cross-link!

**Comment by florianm** [comment]
There's still some gremlins, namely a typo in `set_test_env()` and testthat doesn't seem to read `get_test_{url, key, did, rid}()` - working on it now, will submit another PR once I've got it to work.

**Comment by florianm** [comment]
#32 fixes this issue using Sys.env.
