### ISSUE TITLE
`resource_show` and `package_show` parameters different to CKAN API 2.4a's

### ISSUE THREAD

**Issue by florianm** [ropensci/ckanr#34]
Both [`resource_show` CKAN 2.4a API guide](http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.resource_show) and [`package_show`](http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.package_show) will take parameters:

* id (resource ID),
* include_tracking = FALSE,
* `package_show` only:  `use_default_schema` (bool) – use default package schema instead of a custom schema defined with an IDatasetForm plugin (default: False),

while the API key is not required.

The function docstring is out of date and throws two errors: 
```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'package_show'
  ‘key’
Undocumented arguments in documentation object 'resource_show'
  ‘key’
```

Could I suggest to align ckanR's `resource_show` and `package_show` parameters and docstrings to CKAN's API spec? (see also PR #35 )

**Comment by sckott** [comment]
* The api key is not required - defaults to NULL - I put in those args so that a key can be passed in as another option
* Sorry, forgot to add key param definitions

**Comment by sckott** [comment]
oh, I see. you mean those functions don't need a key, makes sense

**Comment by florianm** [comment]
Happy to put the key back in in #35 if you want. Key param defs also submitted in #35

**Comment by sckott** [comment]
No, it sounds like you are right to take the key params out of those two functions
