### ISSUE TITLE
Which CKAN API version does ckanR implement?

### ISSUE THREAD

**Issue by florianm** [ropensci/ckanr#36]
Apologies for this silly question - are we writing against 2.4a, latest (and keep upgrading), last stable? I'm testing locally on my own branch based on CKAN latest (2.4a) with a few custom plugins (possible problem: custom data schema using ckanext-scheming), and Travic CI is configured to use my public-facing instance `http://data-demo-dpaw.wa.gov.au/` (at least for writing tests).

Also, how do I label this issue as question?

**Comment by sckott** [comment]
labeled as question, i think only repo owners can assign labels

**Comment by sckott** [comment]
The latest version, yes.  I can make that clear in the docs, If there's anything not in sync with latest, let's fix that

**Comment by florianm** [comment]
Understood, thanks! The `\references{}` links to the latest API anyways (another thing to keep updated).
