### ISSUE TITLE
A test server seems to be down

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#38]
@florianm Seems that http://data-demo.dpaw.wa.gov.au//organization/sandbox is down, giving a 500 response, thoughts?

**Comment by florianm** [comment]
I did upgrade the Ckan instance, will double check that data-demo is
functional.

**Comment by sckott** [comment]
thanks, that's okay

**Comment by florianm** [comment]
No luck yet, still diagnosing the problem, will probably take me another day or so! There's something weird going on in my CKAN.

**Comment by florianm** [comment]
Patched the CKAN test server (data-demo.dpaw.wa.gov.au) and tests are passing again.

**Comment by sckott** [comment]
seems fixed now, txh
