### ISSUE TITLE
tag_show tests fail after CKAN API change

### ISSUE THREAD

**Issue by florianm** [ropensci/ckanr#41]
The CKAN's `tag_show` as of early June 2015 [defaults](http://docs.ckan.org/en/latest/api/#ckan.logic.action.get.tag_show) to omit datasets from the result. `ckanr`'s tests assume `include_datasets=TRUE`.

Suggestion: include explicit parameter `include_datasets=FALSE` in `tag_show.R` and adjust tests to use `include_datasets=TRUE`.

**Comment by sckott** [comment]
closed via #42
