### ISSUE TITLE
Download files

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#44]
Files can be lots of things (e.g., csv, xml, jpg, etc.) so this needs to cover various cases

Looks as though there's no proper way in CKAN API to download a file, just have to `GET()` it i guess

**Comment by sckott** [comment]
@Eflores89 okay, reinstall from github, and see the `fetch()` function - you may still want to handle file downloads yourself, but this fxn attempts to read in, with a few formats so far (csv, xls, xml, html, json, shp)

**Comment by Eflores89** [comment]
sounds great! I can't test now, but will in a few hours!! cheers!

**Comment by sckott** [comment]
:+1:
