### ISSUE TITLE
resource description

### ISSUE THREAD

**Issue by jobonaf** [ropensci/ckanr#45]
Is there a way to define resource description with `ds_create_dataset`? Thank you

**Comment by sckott** [comment]
@jobonaf Can you share a link of what you are referring to? Perhaps in the ckan docs?

**Comment by jobonaf** [comment]
http://docs.ckan.org/en/ckan-1.7.2/domain-model-resource.html#standard
> description: A brief description (one sentence) of the Resource

**Comment by florianm** [comment]
@jobonaf just double checking, are you running version 1.7.2? ckanr is written against the current API (2.4 onwards), I'm not sure how much has changed since 1.7.2.

**Comment by sckott** [comment]
That's right, we're developing against the most current version of CKAN

@florianm that sounds right, though I haven't tried it yet.

**Comment by jobonaf** [comment]
> you'll want to get the whole resource dictionary from resource_show, update the values inside that, and httr::POST that dictionary (serialised) back to ckan
something like this?
```
resource_show(pack$results[[1]]$resources[[1]]$id) -> res_dict
res_dict$description  <- "My long description"
POST(url=get_default_url(), key=get_default_key(), body=serializeJSON(res_dict))
```
or like this?
```
...
POST(url="http://ckan.arpa.emr.it/dataset/qualita-dell-aria-valutazione-delle-concentrazioni-di-fondo/resource_edit/", key=get_default_key(), body=serializeJSON(res_dict))
```
anyway, neither the first nor the second way work... probably I'm missing something, I'm not much familiar with httr/RCurl/curl+ckan. Just hoping there was an easy way through ckanr, but probably not yet. Thank you!

**Comment by sckott** [comment]
@jobonaf i'll reopen for a bit until I have time to look into this myself

**Comment by florianm** [comment]
@jobonaf that's interesting - that would have been the CKAN API way of updating data on CKAN - get the dict, update some values, post the dict back. Done so from Python with no troubles on datasets and file attachments. Actually I need your use case implemented as well, so as soon as I've got some play time I'll work on it, unless @sckott is quicker.

**Comment by sckott** [comment]
@jobonaf you can do this now with `resource_patch()`, reinstall newest version first `devtools::install_github("ropensci/ckanr")`
