### ISSUE TITLE
Add resource_create

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#46]
@florianm 

Do you know if this 
http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.create.resource_create

is all the docs there are on `resource_create` API endpoint?  The parameters don't have any explanation as to what they are or what they expect as inputs.

**Comment by florianm** [comment]
@sckott the best I could find is the docstring in the [resource_create source](https://github.com/ckan/ckan/blob/master/ckan/logic/action/create.py#L234).

Note that CKAN also tries to create appropriate resource views (also in create.py) but I haven't stepped through the details of that workflow and hope it automatically runs on `resource_create`.

Is that any good to you?

**Comment by sckott** [comment]
@florianm  thanks  - no descriptions in there, but i'll keep looking
