### ISSUE TITLE
As I package_list my URL is not recognized

### ISSUE THREAD

**Issue by dioh** [ropensci/ckanr#49]
My ckan repository is localhost/api/action but when I read the request, package_list is posting to localhost/api/3/action/package_list

Any thoughts?

**Comment by sckott** [comment]
@dioh what version of CKAN are you using locally?

**Comment by dioh** [comment]
I want the server to automatically give me the latest version as it is
specified in ckan

API versions
<http://docs.ckan.org/en/ckan-2.2/api.html#api-versions>

The CKAN APIs are versioned. If you make a request to an API URL without a
version number, CKAN will choose the latest version of the API:

 "En economía no hay nada misterioso ni inaccesible al entendimiento del
hombre de la calle. Si hay un misterio, reside él en el oculto propósito
que puede perseguir el economista y que no es otro que la disimulación del
interés concreto a que se sirve."

A. Jauretche

**Comment by sckott** [comment]
@dioh Does that mean 2.2?

**Comment by sckott** [comment]
and what version of `ckanr`?

**Comment by dioh** [comment]
Yes, I think it's 2.3

How could I use the URL I mentioned with package_list?

 "En economía no hay nada misterioso ni inaccesible al entendimiento del
hombre de la calle. Si hay un misterio, reside él en el oculto propósito
que puede perseguir el economista y que no es otro que la disimulación del
interés concreto a que se sirve."

A. Jauretche

**Comment by sckott** [comment]
looking at this

**Comment by sckott** [comment]
installing locally to look at it in more detail

How did you install your local CKAN ?

**Comment by dioh** [comment]
Sorry, its not local, it was just an example. Im using this dataset

https://data.hdx.rwlabs.org

**Comment by sckott** [comment]
@dioh This works fine for me

```r
package_list(url = "https://data.hdx.rwlabs.org/")
#> [[1]]
#> [1] "141121-sierra-leone-health-facilities"
#> 
#> [[2]]
#> [1] "1999-2013-tally-of-internaly-displaced-persons-resulting-from-natural-disasters"
#> ...
```

Try that

**Comment by dioh** [comment]
Hi Scott, this works:

package_list(url="https://data.hdx.rwlabs.org/")


This doesn't

package_list(url="http://data.hdx.rwlabs.org")


Sorry for the confusion.


Thanks for your support!


 "En economía no hay nada misterioso ni inaccesible al entendimiento del
hombre de la calle. Si hay un misterio, reside él en el oculto propósito
que puede perseguir el economista y que no es otro que la disimulación del
interés concreto a que se sirve."

A. Jauretche

**Comment by sckott** [comment]
Great
