### ISSUE TITLE
S3 classes for packages, resources, any other objects

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#51]
Before we send 1st version to CRAN, perhaps it makes sense to think about whether it makes sense to create lite-weight  S3 classes to wrap up the data given back representing packages and resources. And any other common objects that CKAN API returns. 

e.g., a S3 class for packages could look like this when printed:

```r
<package> 27778230-2e90-4818-9f00-bbf778c8fa09
  name: foo-bar
  revision_timestamp: 2014-10-28T18:13:22.213530 
  description: Data dictionary for CSTMC artifact datasets
  size: 20 mb
  format: XLS
```

Those things printed could be easily modified based on consensus opinion here. 

In addition to how packages and resource objects are printed to the screen, functions that perform operations on packages/resources could accept an object of class e.g., `ckan_pkg` or `ckan_res`, respectively, in addition to accepting a package or resource ID - This makes it more brainless (easier) to do simultaneous operations on packages or resources.

**Comment by sckott** [comment]
@florianm @wush978 @imanuelcostigan Would love your feedback on this. 

I've pushed a few changes to master regarding this issue. I've stared with CKAN packages just to see how we like it. Here's some examples of how they work:

`package_search()` example

```r
(pkgs <- package_search(rows = 2))
#> $count
#> [1] 334
#> 
#> $sort
#> [1] "score desc, metadata_modified desc"
#> 
#> $facets
#> named list()
#> 
#> $results
#> $results[[1]]
#> <CKAN Package> 
#>   Title: owls6
#>   ID: c1e9baa8-abac-49d7-b84e-b8929731001b
#>   Creator/Modified: 2015-10-08T23:49:50.936630 / 2015-10-08T23:51:04.069287
#>   Resources (up to 5): 
#>   Tags (up to 5): 
#>   Groups (up to 5): 
#> 
#> $results[[2]]
#> <CKAN Package> 
#>   Title: foobar
#>   ID: 585d7ea2-ded0-4fed-9b08-61f7e83a3cb2
#>   Creator/Modified: 2015-08-15T07:09:01.413937 / 2015-10-08T23:48:59.845381
#>   Resources (up to 5): 
#>   Tags (up to 5): 
#>   Groups (up to 5): 
#> 
#> 
#> $search_facets
#> named list()
```

Can use `as.ckan_package()`  to coerce various things to a `ckan_package` class

```r
as.ckan_package("0699f475-6978-473a-8448-42585074b6f1")
#> <CKAN Package> 
#>   Title: !hello world!
#>   ID: 0699f475-6978-473a-8448-42585074b6f1
#>   Creator/Modified: 2015-10-08T17:35:14.891081 / 2015-10-08T17:35:27.722031
#>   Resources (up to 5): 
#>   Tags (up to 5): 
#>   Groups (up to 5):

# an object of class ckan_package gives back itself
x <- as.ckan_package("0699f475-6978-473a-8448-42585074b6f1")
as.ckan_package(x)
#> <CKAN Package> 
#>   Title: !hello world!
#>   ID: 0699f475-6978-473a-8448-42585074b6f1
#>   Creator/Modified: 2015-10-08T17:35:14.891081 / 2015-10-08T17:35:27.722031
#>   Resources (up to 5): 
#>   Tags (up to 5): 
#>   Groups (up to 5): 
```

Most of the `package_*()` functions both take in either objects of class `ckan_package` or something that can be coerced to that, and some give back that same thing. This makes it easy to pipe output of one fxn to another - if one swings that way (I do!), e.g., imagine the following

```r
# note that this won't actually work yet
package_create() %>% 
  resource_create(file = "path/to/file") %>% 
  tag_create() %> 
  etc.  ....
```

We do allow users to toggle the `as` parameter in most functions to give back raw JSON, parsed JSON to a list, or try to parse to a data.frame if possible. This whole workflow of working with `ckan_package` classes will only work with the default, data given back as a list. Given that, is that acceptable?  Too confusing for users?

**Comment by florianm** [comment]
@sckott geez that looks really nice. As in, cleaner than using Python to migrate packages or harvest crazy custom [things](http://catalogue.alpha.data.wa.gov.au/dataset/slip-harvesting/resource/172150c7-b0c5-4f7c-bf1b-44514eb8e5d7) into CKAN.

As I'm wrapping ckanR inside my reports, my end users will be fine with your improvements, if not happier. As long as there's working examples in the docs, they should be fine IMHO.

Big +1

**Comment by sckott** [comment]
@florianm  Glad you like it. Unless there's any objections from others, I'll continue with these changes where they make sense.

**Comment by wush978** [comment]
Great work! I like this feature.

**Comment by sckott** [comment]
seems good for now, open new issues as needed
