### ISSUE TITLE
demo CKAN server 500 status

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#52]
http://data-demo.dpaw.wa.gov.au/

<img width="1006" alt="screen shot 2015-10-08 at 3 22 47 pm" src="https://cloud.githubusercontent.com/assets/577668/10381533/736361f2-6dd0-11e5-831b-76c4a1e23480.png">

@florianm

**Comment by florianm** [comment]
@sckott and it's back! This happens when solR runs out of RAM. We're punishing the server at the moment with some heavy internal use.
Currently building a more robust CKAN for data.wa.gov.au, will replace data-demo with another test instance within the next month.

**Comment by sckott** [comment]
great, thanks!
