### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#53]
The Open Canada CKAN instance has an e.g., where they have links to a CSV, but it's actually a link to a http file server with directories with directories within those, that eventually have actual csv files. 

http://open.canada.ca/data/en/dataset/9ec91c92-22f8-4520-8b2c-0f1cce663e18

3 of the links there are actually csv's, the first is not - this one http://ec.gc.ca/data_donnees/data/water/quality/freshwater/longterm/bc/FraserRiverBasin

**Comment by florianm** [comment]
The [package_show](http://open.canada.ca/data/en/api/3/action/package_show?id=9ec91c92-22f8-4520-8b2c-0f1cce663e18) advertises the resource type as "file", although the [dataset](http://open.canada.ca/data/en/dataset/9ec91c92-22f8-4520-8b2c-0f1cce663e18) advertises the format as "CSV".

open.canada.ca is a highly customised CMS + CKAN. The CKAN side is pretty much spearheading bilingual support, and also follows some [accessibility rules](https://github.com/open-data/ckanext-wet-boew) which change the appearance significantly.

So getting data out of open.canada.ca is a pretty advanced use case, as the base url `http://open.canada.ca/data/` and the language prefix `en/` are non-standard and the bilingual support puts another layer of duplication/translation on top.

If you're looking for a non-CMS-wrapped use case, we'll soon soft-launch the [datacats-based](http://govhack2015.readthedocs.org/) data portal http://catalogue.beta.data.wa.gov.au/ (uat instance at http://catalogue.alpha.data.wa.gov.au/). Also, [ckan o' sweave](https://github.com/datawagovau/ckan-o-sweave) shows a use case of ckanR.

**Comment by sckott** [comment]
Right, that is a pretty advanced use case. 

> If you're looking for a non-CMS-wrapped use case

Yeah, that'd be great

> Also, ckan o' sweave shows a use case of ckanR

Nice!

**Comment by florianm** [comment]
Ok, use cases:

Overview and link to video on CKAN blog showing R scripts, notebooks, and ckan o' sweave in action:
http://catalogue.alpha.data.wa.gov.au/dataset/data-wa-gov-au

Example CSV & R code using ckanR & product generated and uploaded by R code:
http://catalogue.alpha.data.wa.gov.au/dataset/example-dataset

**Comment by sckott** [comment]
thanks for these

**Comment by florianm** [comment]
Update on above links: LinkDigital revamped my datacats-based prototype into an AWS-orchestrated and CMS-wrapped portal which now runs at https://data.wa.gov.au/.
@keithamoss is in charge of the portal.

See https://ckan.org/2016/10/13/enterprise-ckan-stack-for-aws-is-now-available-on-github/

**Comment by sckott** [comment]
thanks @florianm
