### ISSUE TITLE
resource_view 

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#55]
I played around with these, but can't seem to find enough documentation to correctly use them. Anyone?  I found https://github.com/ckan/ckan/wiki/Resource-Views but at least one missing piece is that they don't  explain the possible values to pass to `view_type`

**Comment by florianm** [comment]
resource_view [api docs](http://docs.ckan.org/en/latest/api/index.html?highlight=resource%20view#ckan.logic.action.create.resource_view_create)

`view_type` can be any of the available [resource previews](http://docs.ckan.org/en/latest/maintaining/data-viewer.html#available-view-plugins) such as `text_view`, `image_view`, `recline_view`, `pdf_view`, `webpage_view`, `geojson_view`, `geo_view` plus any additional resource preview types from ckan extensions, e.g. ckanext-cesiumpreview's `cesium_viewer`.

The comprehensive list would be as configured in the CKAN's config `ckan.plugins` and `ckan.views.default_views`.

The main use case for resource previews is to batch create missing resource previews through paster, server side: `paster views create` - docs are [here](http://docs.ckan.org/en/latest/maintaining/data-viewer.html#command-line-interface).

**Comment by sckott** [comment]
@florianm thanks !

**Comment by florianm** [comment]
Revisiting this issue, creating resource views is closely coupled to eyeballing the resulting (working or broken) resource views in CKAN itself. This is more a maintenance/admin task than a data engineering / data access task.

The lazy way would be to let CKAN admins bulk create those trough `paster` commands (no one else should bulk-modify CKAN content), the harder way would be to include (at least as working example) tests for whether the resource previews work (load with status 200?) after creating them, and having a way to delete resource previews (but only broken ones) in case things went wrong. There are CKAN plugins to automatically test for broken content (possibly also broken resource previews), so this whole workflow is a deep rabbit hole.

**Comment by sckott** [comment]
thx for revisiting. sounds complicated. maybe we should close this?

**Comment by florianm** [comment]
I'm in favour of closing until there's a strong use case. 

Wearing my CKAN instance admin hat, I'd rather do these actions through the CKAN CLI (paster) and see any errors directly on the CLI/GUI rather than through the added abstraction level of using an API wrapper (ckanr).

Wearing my data engineer hat, I'd say ckanr's scope is working on the content of CKAN (resources) as in building reports and apps based on data from CKAN resources, and less working on CKAN's config/GUI/built-in visualisations.

**Comment by sckott** [comment]
i haven't used paster but i'd agree in your take here, closing
