### ISSUE TITLE
Any package API changes?

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#56]
@florianm @wush978 @imanuelcostigan 

I would like to get the first version on CRAN soon so we can get it in front of more eyes, to get more use cases, feedback on the pkg.  Do you notice anything that should be changed in the package API before we do this?  Ideally I'd rather not change anything major after getting on CRAN so as not to break people's code.

**Comment by wush978** [comment]
@sckott

I want to test the package again and review the API this week. Could I give you the feedback before 10/18?

**Comment by sckott** [comment]
Sounds good

**Comment by wush978** [comment]
I checked these changes with a CKAN test server. Overall, I like these new features. 

According to what I observed, the information provided by S3 requires more queries to the server. It might introduce some bugs because I just see one. I guess we need to review the testing scripts and everything will be ok.

**Comment by florianm** [comment]
I'm just testing the latest master. Observations: 

* default ckan url in ckanr_setup.R has trailing slash
* if I run ckanr_setup(url=xxx), there must be absolutely no trailing slash - I remember spending too much time figuring out that the trailing slash broke things. Maybe handle trailing slashes more leniently?
* make check: readxl package suggested but not available. Installed, check passes.
* make test: tests fail on trailing slash in ckan url but pass without trailing slash in ckan url.
* tests pass and say I rock. How did they know? \m/
* https://github.com/datawagovau/ckan-o-sweave works fine with latest ckanr. ckanr rocks.

Apart from making the ckan url Florian-proof, ckanr looks good to go from my end!

**Comment by sckott** [comment]
> default ckan url in ckanr_setup.R has trailing slash - if I run ckanr_setup(url=xxx), there must be absolutely no trailing slash - I remember spending too much time figuring out that the trailing slash broke things. Maybe handle trailing slashes more leniently? - make test: tests fail on trailing slash in ckan url but pass without trailing slash in ckan url.

will fix, yes, needs to be smarter for sure

> make check: readxl package suggested but not available. Installed, check passes.

Where do you see this? Running the `fetch` examples?

> tests pass and say I rock. How did they know? \m/

:smiley: 

> https://github.com/datawagovau/ckan-o-sweave works fine with latest ckanr. ckanr rocks.

:smile_cat:

**Comment by sckott** [comment]
I think this error is sufficient (reprod. example):

```r
ckanr_setup()
res <- resource_show(id = "f4f871ae-139f-4acd-a700-8a08a1a04f95", as = "table")
fetch(res$url)
#> Error: Please install readxl
```

**Comment by florianm** [comment]
Morning everyone. Unfortunately I didn't keep the check log from the readxl error. I believe it was during the "check package dpendencies" step, but in any case I had to install readxl (and rid my ckan url of the trailing slash) to get check to pass.

**Comment by sckott** [comment]
@florianm i think the trailing slash thing shuld be fixed here https://github.com/ropensci/ckanr/commit/b7545b9d9879fde5b1fbb7a5f05b2fc4425be621#diff-e549505eb95036528ca3b125f62915a6R20

**Comment by florianm** [comment]
@sckott looks good to me! That's a major source of user confusion on my end, definitely good to allow both trailing and naked end.
