### ISSUE TITLE
Use of POST-Requests instead of GET

### ISSUE THREAD

**Issue by fidelthomet** [ropensci/ckanr#67]
Some functions (e.g. package_list & package_search) use POST-Requests (`ckan_POST`) all-tough they would only need `ckan_GET` (which doesn't seem to be used at all in ckanr). 

This isn't a problem for most CKAN-instances. However, [Zurich's Open Data Portal](https://data.stadt-zuerich.ch/) blocks all POST request from out of the cities internal network. Using only POST-Request makes it therefore impossible to use ckanr with this data portal

**Comment by sckott** [comment]
I've asked around about this, will get back to you soon

**Comment by fidelthomet** [comment]
Thanks

**Comment by sckott** [comment]
@fidelthomet try it again now after reinstalling from there, `devtools::install_github("ropensci/ckanr")` - changed all possible fxns to use GET I think. Here's the ones that still use `POST`

* `ds_create_dataset()`
* `group_create()`
* `group_delete()`
* `group_patch()`
* `group_update()`
* `organization_create()`
* `package_create()`
* `package_delete()`
* `package_patch()`
* `package_update()`
* `related_create()`
* `related_delete()`
* `related_update()`
* `resource_delete()`
* `resource_patch()`
* `resource_create()`
* `resource_update()`
* `tag_create()`

**Comment by fidelthomet** [comment]
Thanks, works great!
