### ISSUE TITLE
Ability to change default base URL

### ISSUE THREAD

**Issue by imanuelcostigan** [ropensci/ckanr#7]
This could for example be implemented using a session option:
```R
set_ckan_url <- function (url = "http://data.techno-science.ca") option(ckan.default.url = url)
get_ckan_url <- function () getOption("ckan.default.url")
```
And then pass this output of this function to other ckanr functions such that ckanr function interfaces would be modified for e.g. as follows:

```R
package_list(offset = 0, limit = 31, url = get_ckan_url(), as = "list", ...)
```

I'll submit a pull request.

**Comment by sckott** [comment]
@imanuelcostigan that sounds reasonable, thanks
