### ISSUE TITLE
Error in resource_create

### ISSUE THREAD

**Issue by mingbogo** [ropensci/ckanr#75]
I was able to run all `resource_*()` functions with the exception of `resource_create()`. I did the following:

```r
resource_create(package_id= package_id,
                rcurl=url,
                description="newdata",
                name="newdataset",
                as="table")
```

It turns an error "Error in file.exists(path) : invalid 'file' argument" no matter what rcurl value I set (local csv path, cloud csv path, existing resource url).

**Comment by sckott** [comment]
Thanks for the report - i think you're looking for the `upload` parameter for the file to upload, I think has to be a local file, and not one at a url  - the `rcurl` param is for the url of resource

I'll have a look in the morning in more detail

**Comment by mingbogo** [comment]
Thanks for your quick response Scott. 

I am not sure what `rcurl` is used for, since my understanding of `resource_create` is to create a new resource under the package_id.

**Comment by sckott** [comment]
that `rcurl` param links to the `url` param here in the docs http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.create.resource_create

**Comment by sckott** [comment]
@mingbogo try it again after reinstalling like `devtools::install_github("ropensci/ckanr")` 

`upload` was not required, but we weren't handing it appropriately internally, - now it actually is optional - and your above eg should work. let me know what happens.

**Comment by mingbogo** [comment]
Thanks Scott. I will try this out soon and will let you know the results.

**Comment by mingbogo** [comment]
Tested and `resource_create` works. However, `rcurl` is not a necessary input. I tried the following and it successfully added my resource to the package, where `rcurl` is not given value:

```
resource_create("caf2cdd4-95ce-4241-a97e-ff76e5624dd4",
                rcurl="",
                name="123test04",
                description="123testr04",
                upload="mystery2.csv")
```

**Comment by sckott** [comment]
> `rcurl` is not a necessary input

Correct. You don't need to pass a `rcurl` value. Did you try a call without it?  It should work.

**Comment by mingbogo** [comment]
Tried `rcrul=""` in `resource_create` function and it worked, but the function still considers `rcurl` as a requirement. I put a proposed fix to the `resource_create` r file for your consideration.

**Comment by sckott** [comment]
Yeah, CKAN does want a URL  - 

> I put a proposed fix to the resource_create r file for your consideration.

where? do you mean just passing `""` ?

**Comment by sckott** [comment]
this is sorted
