### ISSUE TITLE
missing methods

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#76]
I think we need `db_query_fields` and `db_query_rows` methods - and possibly others, but that's where I got errors trying out examples.  - haven't been able to figure those out yet, getting errors on `fetch()`/`dbFetch()` - it's not clear why it's not working - 

and I wonder if we should be developing against dev version of `dplyr` or stable - there's some changes there  - forcing dev dplyr for now, can easily switch back

cc @wush978

**Comment by mingbogo** [comment]
If there is anything I can help with, please let me know.

**Comment by sckott** [comment]
@mingbogo will do, waiting to see what wush has to say

**Comment by wush978** [comment]
I see the following error:

```
> res <- fetch(qry, 0)
Error in .valueClassTest(ans, "data.frame", "fetch") : 
  invalid value from generic function ‘fetch’, class “list”, expected “data.frame”
```

This error is thrown at here:

https://github.com/ropensci/ckanr/blob/master/R/dbi.R#L182

As I remember, the `res@value$records` should be a `data.frame`, but it is a `list` now. I suggest to transform the `res@value$records` to `data.frame` (`res@value$fields` is the schema) and this error should be fixed.

**Comment by sckott** [comment]
>  I suggest to transform the res@value$records to data.frame

where?

**Comment by wush978** [comment]
Before `return` at https://github.com/ropensci/ckanr/blob/master/R/dbi.R#L183

**Comment by wush978** [comment]
https://github.com/ropensci/ckanr/blob/master/R/dbi.R#L63 might be a better place. I'll send a PR

**Comment by sckott** [comment]
okay, thanks

**Comment by sckott** [comment]
> If there is anything I can help with, please let me know.

Thanks, will do!

**Comment by wush978** [comment]
Dear @sckott ,

Finally, I find a method to write a general test for API of dplyr. But it only works for `dplyr::filter` ... and there is nothing I can do with the rest of them. Therefore, I disable all the unit tests except the one for `dplyr::filter`.

Please check:

https://github.com/ropensci/ckanr/compare/master...wush978:develop/76?expand=1

I'll open the PR if there is no further issues.

**Comment by sckott** [comment]
thanks!, looking at the PR
