### ISSUE TITLE
differents between ds_create_dataset() and resource_create()

### ISSUE THREAD

**Issue by GloriaDomenico** [ropensci/ckanr#79]
Hello, 
Using the ckanr library, I've got a issue about the differents between ds_create_dataset() and resource_create(). 
I mean: their outputs look the same and their arguments also. 
This confuse me a little bit: maybe is there a subtle different that i don't get? 
Thanks!

**Comment by sckott** [comment]
Hi @GloriaDomenico - thanks for the issue. 

That's a good question because they do appear to use the same CKAN API routes. The datastore API http://docs.ckan.org/en/latest/maintaining/datastore.html#the-datastore-api doesn't even have a create_dataset route on it, though does have `datastore_create` which _Adds a new table to the DataStore._, which we implement in `ds_create()`

I have a note that `ds_create()` doesn't work right now, i'll look into that one

By the way what are you looking to do?

**Comment by GloriaDomenico** [comment]
Hi @sckott thanks for your reply: it helped me a lot. 
I am using your package to write a code for the managing of our CKAN website with R. 
it is very useful!
I have noticed that do not exist a way to create new users with ckanr, is it right?
All in all, I am not really able to use tag_create(). I have tried in very different ways but I always get this message:
Error: Not working yet
I cannot understand why.
Thank you!

**Comment by mingbogo** [comment]
Perhaps the difference between ds_create_dataset() and resource_create() is the way data interacts with data stores? If data store and pusher are not enabled, then ds_create_dataset() may not work.

**Comment by sckott** [comment]
@GloriaDomenico 

> I have noticed that do not exist a way to create new users with ckanr, is it right?

right, we don't have a function for that yet, docs here http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.create.user_create

> I am not really able to use tag_create()

Sorry about that, if you look at the code https://github.com/ropensci/ckanr/blob/master/R/tag_create.R it's not working yet, so we just put a message in there saying that, will ping you here soon once it's working.

**Comment by sckott** [comment]
@mingbogo sort of correct. i screwed up and used a non datastore api route for `ds_create_dataset` at some point, so it would surprisingly work when datastore isn't enabled. HOWEVER, it shouldn't work if datastore isn't enabled. I'll be updating `ds_create_dataset()` or removing it

**Comment by GloriaDomenico** [comment]
Dear @sckott,
Thank you so much for your very useful explanations.  
Everything is clear now!! 
Kind regards

**Comment by sckott** [comment]
@GloriaDomenico opened issues for removing `ds_create_dataset()`, for fixing `tag_create`, and for adding `user_create`
