### ISSUE TITLE
organization_delete issue

### ISSUE THREAD

**Issue by GloryPassarello** [ropensci/ckanr#83]
Goodmorning, 
I cannot find a way to delete an organization using the ckanr package?
I always did it manually on the website interface and after that I have noticed that I cannot rewrite the same organization using  same name used before on the organization_create() function.
I don't know why, maybe is there a different way to delete an organization ?
Thank you so much

**Comment by sckott** [comment]
Hi, Thanks for your message. WE don't have all organization api methods in the package yet. We'll add it http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.delete.organization_delete and other organization methods
