### ISSUE TITLE
extras in package_patch

### ISSUE THREAD

**Issue by sckott** [ropensci/ckanr#94]

**Comment by sckott** [comment]
clarification desired on how to do extras,

**Comment by sckott** [comment]
@florianm Any thoughts on `extras` with respect to `package_patch` and/or `package_update`?

i thought i had it figured out, that we just pass in arbitrary key-value pairs in a list (which gets sent to CKAN API as JSON), but that doesn't seem to work. those extras fields are just ignored. searching around https://github.com/ckan/ckan/issues it seems that maybe there is a filter puling out only certain named keys - and ignoring the rest. 

fyi, this is using demo.ckan.org, running on ckan v2.5.2

**Comment by florianm** [comment]
extras are a dict with user-defined keys. 

However, some extensions like ckanext-scheming override extras with their custom, predefined fields. This allows CKAN to implement custom dataset schemas. To make it more interesting, scheming allows the schemas to live in your own ckan extension. I can't tell whether demo.ckan.org implements a custom schema, likely not.

Other extensions, like ckanext-spatial, expect defined keys in the extra dict (here: "spatial" containing a GeoJSON Polygon geom). The [demo.ckan.org API](http://demo.ckan.org/api/util/status) shows it has spatial extensions enabled.

Vanilla CKANs should allow creation of arbitrary extra fields. CKANs with custom (ckanext-scheming) schemas will have strong words (in the 500 range) with you if you create an unexpected key in "extras".

From what I can see, I'd expect demo.ckan.org to allow custom extra fields.
To patch/update, you definitely want to read in and post back any extra fields as not to lose them.

**Comment by sckott** [comment]
@florianm okay, i've tried passing in extra fields but hasn't worked. both in a key in the body called `extras` and just arbitrary key-value pairs in the body. Know of any examples of extras working?

**Comment by florianm** [comment]
@sckott found one: https://demo.ckan.org/api/3/action/package_show?id=demo-ckan-org-dataset-bob-orlowski
