### ISSUE TITLE
ORCID identifiers and search keywords for JSON-LD metadata

### ISSUE THREAD

**Issue by chrisfan24** [ropensci/ckanr#99]
👋  @sckott  @wush978  @florianm @imanuelcostigan 

I'm using codemetar to to create JSON-LD metadata for this package and it'd be great if I could get some info from each of the authors. if all of you could comment with your ORCID identifier (except for @sckott since I already have yours) along with keywords for the package that would help for search, it'd be great!

Thanks 😃

**Comment by florianm** [comment]
Hi @chrisfan24 that's mighty nice of you, thanks! My orcid is http://orcid.org/0000-0003-4269-4242

**Comment by sckott** [comment]
@wush978 and @imanuelcostigan do you have ORCIDs?

**Comment by wush978** [comment]
@chrisfan24 thanks. My orcid is http://orcid.org/0000-0001-5180-0567

**Comment by sckott** [comment]
@chrisfan24 here's some keywords: 

`database`, `open data`, `ckan`, `api`, `data`, `dataset`
